//
//  Color+FlowerTheme.swift
//  FlowersWidget
//
//  Created by James Frewin on 24/07/2025.
//

import SwiftUI

// The color assets are automatically generated by Xcode
// We can add additional convenience colors here if needed

extension Color {
    // Additional UI element colors that aren't in assets
    static let flowerSecondary = Color.blue
    static let flowerSheetBackground = Color(.systemBackground)
    static let flowerBackgroundSecondary = Color(.secondarySystemBackground)
    static let flowerTextTertiary = Color(.tertiaryLabel)
    static let flowerButtonBackground = Color(.systemGray6)
    static let flowerInputBackground = Color(.systemGray6)
    static let flowerDivider = Color(.separator)
    static let flowerSuccess = Color.green
    static let flowerError = Color.red
}